version: '3.1'

services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: database1
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080