spring:
    security:
        user:
            name: admin
            password: admin
    datasource:
        url: jdbc:mysql://localhost:3306/database1
        username: root
        password: rootpwd
    jpa:
        hibernate:
            ddl-auto: update #create-drop

